In [2]:
import numpy as np

array = np.array([
    [1, 2, 3, 4],  # Added a comma at the end
    [2, 3, 4, 5],  # Added a comma at the end
    [5, 6, 7, 8]   # Replaced periods with commas
])

print(array)


[[1 2 3 4]
 [2 3 4 5]
 [5 6 7 8]]


In [6]:
array.shape

array.size

12

In [8]:
array.dtype


dtype('int64')